title: Grundschule am Gartenfeld

description: >
  Website der Grundschule am Gartenfeld.

lang: de

url: ""
baseurl: ""

navbar_fixed: true
footer_fixed: true

max_width: 930px

back_to_top: true

enable_math: false
enable_tooltips: false
enable_darkmode: false
enable_project_categories: false
enable_medium_zoom: false
enable_progressbar: false
enable_video_embedding: false

collections:
  news:
    output: true

include:
  - "_pages"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

theme: al_folio_core

plugins:
  - al_folio_core
  - al_icons
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed