title: Grundschule am Gartenfeld

description: >
  Website der Grundschule am Gartenfeld.

lang: de

url: https://moritzgroh.github.io
baseurl: /gag-Website

navbar_fixed: true
footer_fixed: true

max_width: 930px

back_to_top: true

enable_math: true
enable_tooltips: false
enable_darkmode: true
enable_project_categories: false
enable_medium_zoom: false
enable_progressbar: true
enable_video_embedding: false

collections:
  news:
    output: true

include:
  - "_pages"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

theme: al_folio_core

plugins:
  - al_folio_core
  - al_icons
  - jekyll-feed
  - jekyll-sitemap
  - al_math

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

third_party_libraries: {}